# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='wppost',
            name='categories',
            field=models.ManyToManyField(blank=True, to='wagtailpress.Category'),
        ),
        migrations.AlterField(
            model_name='wppost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
